Twitter handler
addianto/botofculture-discord pull request #3
Opened 2020-07-18 16:38 UTC by adrika-novrialdi

Add functionality for sending images from twitter's link. This implementation is using twitter API for python. 

In general, the implementation add more configuration needed for environment variable (the env needed are listed in README.md). 

I also move some functionality that used by both of the handler into a new file. 

This implementation also has supported NSFW filter from twitter but it is not 100% accurate. At this implementation, if that tweet is categorized as NSFW, all the image in the tweet will be spoiler-ed.

2020-07-19 14:57 UTC, addianto requested changes
Please make sure all functions are properly type hinted.

2020-07-19 14:57 UTC, addianto commented on botofculture/twitter_service.py
> +async def handle(message: discord.message):
The type hint in the parameter should be `message: discord.Message`.

2020-07-19 14:57 UTC, addianto commented on botofculture/twitter_service.py
> +async def parse_image(file_url, message: discord.message, is_nsfw):
The type hint for `message` parameter should be `discord.Message`. Similarly, `is_nsfw` parameter should have type hint `bool`.

2020-07-19 14:57 UTC, addianto commented on botofculture/twitter_service.py
> +def is_nsfw(status_data):
`status_data` is a `dict` I presume?

2020-07-20 02:00 UTC, adrika-novrialdi commented
Changes implemented. All Functions listed has used type hint in the parameter.

2020-07-20 02:05 UTC, addianto approved these changes
LGTM. 👍

2020-07-20 03:49 UTC, merged